---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: compositekubernetesclusters.common.crossplane.io
  labels:
    rbac.crossplane.io/aggregate-to-crossplane: "true"
rules:
  - apiGroups:
      - common.crossplane.io
    resources:
      - compositekubernetesclusters
      - compositekubernetesclusters/status
      - kubernetescluster
      - kubernetescluster/status
    verbs:
      - "*"
