---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: compositemachineinstances.common.crossplane.io
  labels:
    rbac.crossplane.io/aggregate-to-crossplane: "true"
rules:
  - apiGroups:
      - common.crossplane.io
    resources:
      - compositemachineinstances
      - compositemachineinstances/status
      - machineinstance
      - machineinstance/status
    verbs:
      - "*"
