---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: compositemysqlinstances.common.crossplane.io
  labels:
    rbac.crossplane.io/aggregate-to-crossplane: "true"
rules:
  - apiGroups:
      - common.crossplane.io
    resources:
      - compositemysqlinstances
      - compositemysqlinstances/status
      - mysqlinstance
      - mysqlinstance/status
    verbs:
      - "*"
