---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: compositenosqlinstances.common.crossplane.io
  labels:
    rbac.crossplane.io/aggregate-to-crossplane: "true"
rules:
  - apiGroups:
      - common.crossplane.io
    resources:
      - compositenosqlinstances
      - compositenosqlinstances/status
      - nosqlinstance
      - nosqlinstance/status
    verbs:
      - "*"
