---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: compositepostgresqlinstances.common.crossplane.io
  labels:
    rbac.crossplane.io/aggregate-to-crossplane: "true"
rules:
  - apiGroups:
      - common.crossplane.io
    resources:
      - compositepostgresqlinstances
      - compositepostgresqlinstances/status
      - postgresqlinstance
      - postgresqlinstance/status
    verbs:
      - "*"
