---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: compositeredisclusters.common.crossplane.io
  labels:
    rbac.crossplane.io/aggregate-to-crossplane: "true"
rules:
  - apiGroups:
      - common.crossplane.io
    resources:
      - compositeredisclusters
      - compositeredisclusters/status
      - rediscluster
      - rediscluster/status
    verbs:
      - "*"
