---
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: CompositeResourceDefinition
metadata:
  name: compositemachineinstances.common.crossplane.io
spec:
  claimNames:
    kind: MachineInstance
    plural: machineinstances
  crdSpecTemplate:
    group: common.crossplane.io
    version: v1alpha1
    names:
      categories:
        - crossplane
      kind: CompositeMachineInstance
      plural: compositemachineinstances
