---
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: CompositeResourceDefinition
metadata:
  name: compositemysqlinstances.common.crossplane.io
spec:
  claimNames:
    kind: MySQLInstance
    plural: mysqlinstances
  connectionSecretKeys:
    - username
    - password
    - endpoint
    - port
  crdSpecTemplate:
    group: common.crossplane.io
    version: v1alpha1
    names:
      categories:
        - crossplane
      kind: CompositeMySQLInstance
      plural: compositemysqlinstances
    validation:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              version:
                description: Version specifies the desired MySQL engine version,
                  e.g. 5.7.
                enum:
                  - "5.6"
                  - "5.7"
                type: string
              storageGB:
                type: integer
            required:
              - version
              - storageGB
