---
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: CompositeResourceDefinition
metadata:
  name: compositeredisclusters.common.crossplane.io
spec:
  claimNames:
    kind: RedisCluster
    plural: redisclusters
  connectionSecretKeys:
    - endpoint
    - password
    - port
  crdSpecTemplate:
    group: common.crossplane.io
    version: v1alpha1
    names:
      categories:
        - crossplane
      kind: CompositeRedisCluster
      plural: compositeredisclusters
    validation:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              version:
                description: Version specifies the desired Redis version.
                enum:
                  - "2.6"
                  - "2.8"
                  - "3.2"
                  - "4.0"
                  - "5.0"
                type: string
            required:
              - version
