---
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: CompositeResourceDefinition
metadata:
  name: compositebuckets.common.crossplane.io
spec:
  claimNames:
    kind: Bucket
    plural: buckets
  crdSpecTemplate:
    group: common.crossplane.io
    version: v1alpha1
    names:
      categories:
        - crossplane
      kind: CompositeBucket
      plural: compositebuckets
