---
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: CompositeResourceDefinition
metadata:
  name: compositekubernetesclusters.common.crossplane.io
spec:
  claimNames:
    kind: KubernetesCluster
    plural: kubernetesclusters
  connectionSecretKeys:
    - kubeconfig
  crdSpecTemplate:
    group: common.crossplane.io
    version: v1alpha1
    names:
      categories:
        - crossplane
      kind: CompositeKubernetesCluster
      plural: compositekubernetesclusters
    validation:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              version:
                description: Version specifies the desired Kubernetes version,
                  e.g. 1.15.
                type: string
            required:
              - version
